-- ============================================
-- INSERTAR UNIVERSIDADES DE EL SALVADOR
-- ============================================
-- Departamentos: 1=San Salvador, 2=Santa Ana, 3=San Miguel,
-- 4=La Libertad, 5=Usulutan, 6=Sonsonate, 7=La Union,
-- 8=Cuscatlan, 9=Chalatenango, 10=La Paz, 11=Cabanas,
-- 12=San Vicente, 13=Morazan, 14=Ahuachapan
-- ============================================

INSERT INTO Universidades (nombre, departamento_id) VALUES
('Universidad de El Salvador (UES)', 1),
('Universidad Jose Matias Delgado (UJMD)', 1),
('Universidad Francisco Gavidia (UFG)', 1),
('Universidad Centroamericana Jose Simeon Canas (UCA)', 1),
('Universidad Albert Einstein (UAE)', 1),
('Universidad Autonoma de Santa Ana (UNASA)', 2),
('Universidad Catolica de El Salvador (UNICAES)', 2),
('Universidad Cristiana de las Asambleas de Dios (UCAD)', 1),
('Universidad de Nueva San Salvador (UNSSA)', 1),
('Universidad de Oriente (UNIVO)', 3),
('Universidad de Sonsonate (USO)', 6),
('Universidad Don Bosco (UDB)', 1),
('Universidad Dr. Andres Bello (UAB)', 1),
('Universidad Evangelica de El Salvador (UEES)', 1),
('Universidad Gerardo Barrios (UGB)', 3),
('Universidad Luterana Salvadorena (ULS)', 1),
('Universidad Modular Abierta (UMA)', 2),
('Universidad Monseñor Oscar Arnulfo Romero (UMOAR)', 1),
('Universidad Panamericana de El Salvador (UPAN)', 1),
('Universidad Pedagogica de El Salvador', 1),
('Universidad Politecnica de El Salvador', 1),
('Universidad Salvadoreña Alberto Masferrer (USAM)', 4),
('Universidad Tecnica Latinoamericana (UTLA)', 4),
('Universidad Tecnologica de El Salvador (UTEC)', 1),
('ITCA-FEPADE', 1),
('Escuela Superior de Economia y Negocios (ESEN)', 4),
('Escuela Nacional de Agricultura (ENA)', 4),
('Universidad Internacional Nehemias (NIU)', 1);

-- ============================================
-- INSERTAR CARRERAS
-- ============================================
INSERT INTO Carreras (nombre) VALUES
('Doctorado en Medicina'),
('Licenciatura en Ciencias Juridicas (Derecho)'),
('Licenciatura en Administracion de Empresas'),
('Licenciatura en Psicologia'),
('Ingenieria en Sistemas Informaticos'),
('Licenciatura en Enfermeria'),
('Ingenieria Industrial'),
('Licenciatura en Contaduria Publica'),
('Licenciatura en Idioma Ingles'),
('Licenciatura en Mercadeo'),
('Arquitectura'),
('Ingenieria Civil'),
('Ingenieria Electrica'),
('Ingenieria Mecanica'),
('Ingenieria Agronomica'),
('Licenciatura en Comunicaciones y Periodismo'),
('Licenciatura en Diseno Grafico'),
('Licenciatura en Ciencias de la Educacion'),
('Licenciatura en Matematica'),
('Licenciatura en Quimica y Farmacia'),
('Licenciatura en Trabajo Social'),
('Licenciatura en Biologia'),
('Licenciatura en Economia'),
('Licenciatura en Finanzas'),
('Licenciatura en Hotelería y Turismo'),
('Licenciatura en Relaciones Internacionales'),
('Licenciatura en Sociologia'),
('Ingenieria en Alimentos'),
('Ingenieria Quimica'),
('Licenciatura en Estadistica'),
('Licenciatura en Filosofia'),
('Licenciatura en Historia'),
('Licenciatura en Letras'),
('Licenciatura en Nutricion'),
('Licenciatura en Fisioterapia'),
('Ingenieria en Telecomunicaciones'),
('Licenciatura en Ciencias Politicas'),
('Licenciatura en Administracion de Turismo'),
('Tecnico en Administracion de Ventas'),
('Tecnico en Contabilidad'),
('Ingenieria en Computacion'),
('Licenciatura en Gerontologia'),
('Tecnico en Electronica'),
('Tecnico en Mecanica Automotriz'),
('Tecnico en Desarrollo de Software'),
('Tecnico en Enfermeria'),
('Licenciatura en Bibliotecologia'),
('Licenciatura en Antropologia'),
('Licenciatura en Musicologia'),
('Licenciatura en Educacion Fisica'),
('Licenciatura en Administracion Publica'),
('Licenciatura en Mercadeo Internacional'),
('Ingenieria Ambiental'),
('Ingenieria Biomedica'),
('Licenciatura en Ciencias de la Computacion'),
('Licenciatura en Gastronomia'),
('Tecnico en Logistica'),
('Tecnico en Marketing Digital'),
('Licenciatura en Geologia'),
('Licenciatura en Astronomia');

PRINT 'Catalogos de universidades y carreras insertados.';
GO
